In [1]:
# Imports
import numpy as np

from parcels import (grid, Field, FieldSet, ParticleSet, JITParticle, ScipyParticle, AdvectionRK4,
                     ErrorCode, ParticleFile, Variable, plotTrajectoriesFile)

from datetime import timedelta as delta
from datetime import datetime

import argparse
from glob import glob
import pickle
import xarray as xr
import os.path
import warnings

import sys
sys.path.append('/science/users/4302001/arctic-connectivity/tools')
sys.path.append('/Users/daanreijnders/surfdrive/Thesis/repo/tools')
import fieldsetter_cmems
import kernelCollection
import community
import advectParticles

Stripy is not available on this machine.


In [2]:
fieldset = fieldsetter_cmems.create(20010101, 3, antiBeach=True)

In [4]:
fieldset.U.data[0].shape

(420, 4320)

In [5]:
fieldset.U.grid.lon

array([-180.     , -179.91667, -179.83333, ...,  179.75   ,  179.83333,
        179.91667], dtype=float32)

In [6]:
fieldset.add_periodic_halo(zonal=True)

In [7]:
fieldset.U.grid.lon

array([-180.41667, -180.33333, -180.25   , ...,  180.16667,  180.25   ,
        180.33333], dtype=float32)

In [11]:
np.all(fieldset.U.data[0, :, 0:5] == fieldset.U.data[0, :, -10:-5])

True

In [13]:
fieldset.U_unbeach.grid.lon

array([-180.41667, -180.33333, -180.25   , ...,  180.16667,  180.25   ,
        180.33333], dtype=float32)

In [14]:
fieldset.U.grid.lat

array([55.      , 55.083332, 55.166668, 55.25    , 55.333332, 55.416668,
       55.5     , 55.583332, 55.666668, 55.75    , 55.833332, 55.916668,
       56.      , 56.083332, 56.166668, 56.25    , 56.333332, 56.416668,
       56.5     , 56.583332, 56.666668, 56.75    , 56.833332, 56.916668,
       57.      , 57.083332, 57.166668, 57.25    , 57.333332, 57.416668,
       57.5     , 57.583332, 57.666668, 57.75    , 57.833332, 57.916668,
       58.      , 58.083332, 58.166668, 58.25    , 58.333332, 58.416668,
       58.5     , 58.583332, 58.666668, 58.75    , 58.833332, 58.916668,
       59.      , 59.083332, 59.166668, 59.25    , 59.333332, 59.416668,
       59.5     , 59.583332, 59.666668, 59.75    , 59.833332, 59.916668,
       60.      , 60.083332, 60.166668, 60.25    , 60.333332, 60.416668,
       60.5     , 60.583332, 60.666668, 60.75    , 60.833332, 60.916668,
       61.      , 61.083332, 61.166668, 61.25    , 61.333332, 61.416668,
       61.5     , 61.583332, 61.666668, 61.75    , 